resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to:  /templates'
  inputs:
    Contents: '**/mexl-dev.yaml'

    TargetFolder: '$(build.artifactstagingdirectory)'

    CleanTargetFolder: true

    OverWrite: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: templates'
  inputs:
    ArtifactName: templates
